include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule
    prefer_single_quotes: true
    require_trailing_commas: true
    always_declare_return_types: true
    always_specify_types: true
    always_use_package_imports: true
