name: notion_wordbook
description: A client mobile app that connects to notion.so and allows you to
  view a wordbook.
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=2.16.0-134.5.beta <3.0.0"
  flutter: ^3.0.5

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_riverpod: ^1.0.3
  hooks_riverpod: ^1.0.3
  http: ^0.13.4
  import_sorter: ^4.6.0
  json_annotation: ^4.4.0
  shared_preferences: ^2.0.13
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.19.2

flutter:
  uses-material-design: true
