name: notion_wordbook
description: A client mobile app that connects to notion.so and allows you to
  view a wordbook.
# publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=2.16.0-134.5.beta <3.0.0"
  flutter: ^3.0.5

dependencies:
  change_app_package_name: ^1.1.0
  cupertino_icons: ^1.0.2
  firebase_analytics: ^9.3.0
  firebase_core: ^1.20.0
  firebase_remote_config: ^2.0.13
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_riverpod: ^1.0.3
  hooks_riverpod: ^1.0.3
  http: ^0.13.4
  import_sorter: ^4.6.0
  json_annotation: ^4.4.0
  package_info_plus: ^1.4.3
  shared_preferences: ^2.0.13
  url_launcher: ^6.0.20
  version: ^3.0.2

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
